### PR TITLE
fixing format errors

### PR DESCRIPTION
**Pull request by pnrobinson**
fixing some syntax errors that were introduced in the merge
I think some of the test classes are mixing pytest and unittest and this may be leading to weirdness
I

### CODE REVIEW

**Comment by ielis** [comment]
I may add a bunch of commits. Pls do not merge yet.

**Comment by ielis** [comment]
@pnrobinson 

I wonder if we could drop this class `Iso8601Mapper`. The class probably does not add much since there is no state. All we need is a function that takes something, e.g. a `pd.Series`, and gives us an ISO8601 duration `str`. This is an example of an util function or a protected function on `CdaFactory`.

Next, we need to harmonize parsing the days. We must decide if we want to round the days to years, months, and days. We have two options:
- do NOT round, converting e.g. 1234 days to `P1234D` duration
- DO round, converting 1234 to `P3Y11M10D`

I would prefer the first option, since we will not lose precision. We can always format `P1234D` to years and months using some constants.

Regarding testing framework, the only thing I really care about is being consistent. However, we should probably go for `pytest`.

**Review by ielis — COMMENTED** [review]
@pnrobinson @justaddcoffee 

I wonder if we could drop this class `Iso8601Mapper`. The class probably does not add much since there is no state. All we need is a function that takes something, e.g. a `pd.Series`, and gives us an ISO8601 duration `str`. This is an example of an util function or a protected function on `CdaFactory`.

Next, we need to harmonize parsing the days. We must decide if we want to round the days to years, months, and days. We have two options:
- do NOT round, converting e.g. 1234 days to `P1234D` duration
- DO round, converting 1234 to `P3Y11M10D`

I would prefer the first option, since we will not lose precision. We can always format `P1234D` to years and months using some constants.

Regarding testing framework, the only thing I really care about is being consistent. However, we should probably go for `pytest`.

Pls let me know your thoughts.

**Comment by pnrobinson** [comment]
I am thinking that there may be other time related functions we will need, but yes, this has no state. Having a class makes it easier to test but once dust has settled we can refactor.

Users of the phenopacket will appreciate having P3Y11M10D format if they look at the raw file. There is absolutely no use case for having more significant digits (so to speak), since the clinical data is very noisy and it is likely that in many case the number of days was calculated as age*365. I did not think that P12321D was a valid string, although it does not seem to be forbidden. We can implement this as an option, but then we need to implement more decoding software in applications...

**Comment by pnrobinson** [comment]
What I mean is that the situation is as if calculator displays 17.856239 and 3 significant digits are justified. This is like displaying P23Y2M13DT7H12M when all we know is that P23Y is approximately correct. There is no case in medical analysis where you care about whether P23Y is different from P23Y1M3D. If we display number of days, we are making things more difficult for users without any benefit...

**Comment by ielis** [comment]
@pnrobinson I guess it is a question of scope.

I agree that _some_ analyses at _some_ point may choose to do this type of rounding. However, my understanding is that here we work on ETL software, and the analysis part will live downstream/elsewhere. Therefore, it should _not_ be our decision to round data, unless we absolutely must (we do not).

I am sensitized to this type of scope creep, so I am pointing it out.

**Pull request closed without merging**
