### PR TITLE
Expand CDA to NCIT Mappings for 12 tissues & Enhance OpUberonMapper

### PR DESCRIPTION
**Pull request by rajdeepmondal-el**
This introduces a significant expansion to our CDA to NCIT mappings, featuring a comprehensive addition of twelve CSV files for 12 tissues for CDA to NCIT mappings. These files cover a diverse range of tissues: bone, brain, breast, cervix, colon, heart, kidney, liver, lung, pancreas, skin, and thyroid. Please find these detailed mappings organized in `src/oncoexporter/ncit_mapping_files/cda_to_ncit_tissue_wise_mappings`.

Furthermore, `OpUberonMapper` was updated within `src/oncoexporter/cda/mapper/op_uberon_mapper.py`, adding new terms and mappings that translate the string representations of anatomical locations into their corrosponding UBERON terms.

Kindly please take a look, 

Thanks a lot,
Rajdeep

### CODE REVIEW

**Comment by justaddcoffee** [comment]
great @rajdeepmondal-el ! Maybe we can review tomorrow?

**Comment by justaddcoffee** [comment]
cc: @pnrobinson

**Review by justaddcoffee — COMMENTED** [review]
@rajdeepmondal-el these mappings seem very good

Manually checking these, I did spot 1-2 that probably need updating, e.g. [this one](https://github.com/monarch-initiative/oncoexporter/blob/30a106227c28985b64f9ae6e12585960b57795d3/src/oncoexporter/ncit_mapping_files/cda_to_ncit_tissue_wise_mappings/cda_to_ncit_map_skin.csv#L93) should probably be [NCIT:C3749 Alveolar Rhabdomyosarcoma](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C3749) and not [NCIT:C194245 Malignant Neoplasm of Connective and Soft Tissue of Head, Face and Neck](https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C194245)

Maybe @pnrobinson, you and I could manually review some more of these today on the call?

**Comment by rajdeepmondal-el** [comment]
Thanks a lot for pointing it out, Agree with you @justaddcoffee I can explain why the result is that so, and some probable ways to make the predictions even more accurate. For this specific example, the primary_diagnosis_site consists of quite a lot of spurious information that might make the model a bit confused, it is trying to be more context-aware than necessary, which I can solve by assigning weights to the diagnosis part.

Also, there are some edge cases which i will also share.

**Review by justaddcoffee — APPROVED** [review]
handing this off to @ielis

**Review by ielis — APPROVED** [review]
Hi @rajdeepmondal-el 

thanks a lot for your excellent work!

I plugged the mapping files into the library and tested to run one of the driver script and it looks OK.

It's looking good, please feel free to merge the PR!

**Comment by rajdeepmondal-el** [comment]
Thank you very much @ielis, I have merged it.

**Pull request merged**
